custom.config.prop1= prop1_value_dev_profile
custom.config.prop2= prop2_value_dev_profile
custom.config.prop3[0]= prop3_item1_dev_profile
custom.config.prop3[1]= prop3_item2_dev_profile
custom.config.prop4.key1= prop4_key1_value_dev_profile
custom.config.prop4.key2= prop4_key2_value_dev_profile
custom.config.pojo.pojo-prop1=pojo_str_dev_profile
custom.config.pojo.pojo-prop2[0]=pojo_list_item1_dev_profile
custom.config.pojo.pojo-prop2[1]=pojo_list_item2_dev_profile

my.new.props.string-list-map.key1[0] = val10 dev_profile_properties
my.new.props.string-list-map.key1[1] = val11 dev_profile_properties
my.new.props.string-list-map.key1[2] = val12 dev_profile_properties
my.new.props.string-list-map.key2[0] = val20 dev_profile_properties
my.new.props.string-list-map.key2[1] = val21 dev_profile_properties
my.new.props.string-list-map.key2[2] = val22 dev_profile_properties
my.new.props.pojo-map.pojo-key1.string-set[0] = pojo_map_str_prop valueK1-1 dev_profile_properties
my.new.props.pojo-map.pojo-key1.string-set[1] = pojo_map_str_prop valueK1-2 dev_profile_properties
my.new.props.pojo-map.pojo-key2.string-set[0] = pojo_map_str_prop valueK2-1 dev_profile_properties
my.new.props.pojo-map.pojo-key2.string-set[1] = pojo_map_str_prop valueK2-2 dev_profile_properties
my.new.props.some-prop= some_prop_value dev_profile_properties